// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `ImageData.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package jderobot;

/**
 * A single image served as a sequence of bytes
 **/
public class ImageData extends Ice.ObjectImpl
{
    public ImageData()
    {
    }

    public ImageData(Time timeStamp, ImageDescription description, byte[] pixelData)
    {
        this.timeStamp = timeStamp;
        this.description = description;
        this.pixelData = pixelData;
    }

    private static class __F implements Ice.ObjectFactory
    {
        public Ice.Object
        create(String type)
        {
            assert(type.equals(ice_staticId()));
            return new ImageData();
        }

        public void
        destroy()
        {
        }
    }
    private static Ice.ObjectFactory _factory = new __F();

    public static Ice.ObjectFactory
    ice_factory()
    {
        return _factory;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::jderobot::ImageData"
    };

    public boolean
    ice_isA(String s)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public boolean
    ice_isA(String s, Ice.Current __current)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public String[]
    ice_ids()
    {
        return __ids;
    }

    public String[]
    ice_ids(Ice.Current __current)
    {
        return __ids;
    }

    public String
    ice_id()
    {
        return __ids[1];
    }

    public String
    ice_id(Ice.Current __current)
    {
        return __ids[1];
    }

    public static String
    ice_staticId()
    {
        return __ids[1];
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeTypeId(ice_staticId());
        __os.startWriteSlice();
        timeStamp.__write(__os);
        __os.writeObject(description);
        ByteSeqHelper.write(__os, pixelData);
        __os.endWriteSlice();
        super.__write(__os);
    }

    private class Patcher implements IceInternal.Patcher
    {
        public void
        patch(Ice.Object v)
        {
            try
            {
                description = (ImageDescription)v;
            }
            catch(ClassCastException ex)
            {
                IceInternal.Ex.throwUOE(type(), v.ice_id());
            }
        }

        public String
        type()
        {
            return "::jderobot::ImageDescription";
        }
    }

    public void
    __read(IceInternal.BasicStream __is, boolean __rid)
    {
        if(__rid)
        {
            __is.readTypeId();
        }
        __is.startReadSlice();
        timeStamp = new Time();
        timeStamp.__read(__is);
        __is.readObject(new Patcher());
        pixelData = ByteSeqHelper.read(__is);
        __is.endReadSlice();
        super.__read(__is, true);
    }

    public void
    __write(Ice.OutputStream __outS)
    {
        Ice.MarshalException ex = new Ice.MarshalException();
        ex.reason = "type jderobot::ImageData was not generated with stream support";
        throw ex;
    }

    public void
    __read(Ice.InputStream __inS, boolean __rid)
    {
        Ice.MarshalException ex = new Ice.MarshalException();
        ex.reason = "type jderobot::ImageData was not generated with stream support";
        throw ex;
    }

    /**
     * < TimeStamp of Data
     **/
    public Time timeStamp;

    /**
     * < ImageDescription of Data, for convienence purposes
     **/
    public ImageDescription description;

    /**
     * < The image data itself. The structure of this byte sequence
     * depends on the image format and compression.
     **/
    public byte[] pixelData;
}
